# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 145ac651d85e1078c64563ec721147ceb8b967b6c89fe7873d67bb6fe3327dc8e7e710285b85258209bf8686f3a512a1efe960574cbada08bbdcc028856f5a94

test:
  secret_key_base: d6cbb0d91d101883e1a1a3d05de050944a7b4f9b6924dea69b9cf4eb84666759551d952fd7beef67ddba1738d52b6614b7de265c8fa3e51d80443966a3f7febc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
