# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a027c9d9a577538f93655e22b789c7914918923aadf2fbef4b44977a80b336b339c6bc892cf581d338f1a37528f472b12cd535593ebe973676f9056cc35d89ca

test:
  secret_key_base: f7537ef38b6da5c0f3e1426c57395025b8899c118ae0f9cdf03887265032dd665a8be767edf6b43000acb3dbc5481629bfb93d3afee9a29b966c512fcc338e36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
